en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  title: HuaDeity's Blog
  params:
    subtitle: A blog about programming, life and everything.
    description: A blog about programming, life and everything.
    author:
      email: hello@huadeity.com
      name: HuaDeity
    flag: ğŸ‡ºğŸ‡¸
    giscus:
      lang: en
  weight: 1
zh:
  contentDir: content/zh
  disabled: false
  languageCode: zh-CN
  languageDirection: ltr
  languageName: ç®€ä½“ä¸­æ–‡
  title: åå¥•ç¥å°Šçš„åšå®¢
  params:
    subtitle: ä¸€ä¸ªå…³äºç¼–ç¨‹ã€ç”Ÿæ´»å’Œä¸€åˆ‡çš„åšå®¢ã€‚
    description: ä¸€ä¸ªå…³äºç¼–ç¨‹ã€ç”Ÿæ´»å’Œä¸€åˆ‡çš„åšå®¢ã€‚
    author:
      email: hello@huadeity.com
      name: åå¥•ç¥å°Š
    flag: ğŸ‡¨ğŸ‡³
    giscus:
      lang: zh-CN
  weight: 2
  hasCJKLanguage: true
